# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_aHEcj_t3tnsWf-kMXBg75iDUMVpPqs
"""

import streamlit as st
import joblib
import pandas as pd

# Load model and columns
model = joblib.load("model.pkl")
columns = joblib.load("columns.pkl")

st.title("📊 Customer Churn Prediction")

st.write("Fill in customer details:")

# ---------------- NUMERIC ----------------
SeniorCitizen = st.selectbox("Senior Citizen", [0, 1])
tenure = st.number_input("Tenure (months)", 0, 100)
MonthlyCharges = st.number_input(
    "Monthly Charges ($18 – $120)",
    min_value=18.0,
    max_value=120.0
)

TotalCharges = st.number_input(
    "Total Charges ($18 – $9000)",
    min_value=18.0,
    max_value=9000.0
)

# ---------------- BASIC ----------------
gender = st.selectbox("Gender", ["Female", "Male"])
Partner = st.selectbox("Partner", ["No", "Yes"])
Dependents = st.selectbox("Dependents", ["No", "Yes"])
PhoneService = st.selectbox("Phone Service", ["No", "Yes"])

# ---------------- MULTIPLE LINES ----------------
MultipleLines = st.selectbox(
    "Multiple Lines",
    ["No", "Yes", "No phone service"]
)

# ---------------- INTERNET ----------------
InternetService = st.selectbox(
    "Internet Service",
    ["DSL", "Fiber optic", "No"]
)

# ---------------- ONLINE SERVICES ----------------
OnlineSecurity = st.selectbox(
    "Online Security",
    ["No", "Yes", "No internet service"]
)

OnlineBackup = st.selectbox(
    "Online Backup",
    ["No", "Yes", "No internet service"]
)

DeviceProtection = st.selectbox(
    "Device Protection",
    ["No", "Yes", "No internet service"]
)

TechSupport = st.selectbox(
    "Tech Support",
    ["No", "Yes", "No internet service"]
)

# ---------------- STREAMING ----------------
StreamingTV = st.selectbox(
    "Streaming TV",
    ["No", "Yes", "No internet service"]
)

StreamingMovies = st.selectbox(
    "Streaming Movies",
    ["No", "Yes", "No internet service"]
)

# ---------------- CONTRACT ----------------
Contract = st.selectbox(
    "Contract Type",
    ["Month-to-month", "One year", "Two year"]
)

PaperlessBilling = st.selectbox("Paperless Billing", ["No", "Yes"])

# ---------------- PAYMENT ----------------
PaymentMethod = st.selectbox(
    "Payment Method",
    ["Credit card", "Electronic check", "Mailed check", "Bank transfer"]
)

# ================= PREDICT =================
if st.button("Predict"):

    # Create empty dataframe
    input_data = pd.DataFrame(columns=columns)
    input_data.loc[0] = 0

    # -------- NUMERIC --------
    input_data["SeniorCitizen"] = SeniorCitizen
    input_data["tenure"] = tenure
    input_data["MonthlyCharges"] = MonthlyCharges
    input_data["TotalCharges"] = TotalCharges
    input_data["AvgCharges"] = TotalCharges / tenure if tenure != 0 else 0

    # -------- BASIC --------
    if gender == "Male":
        input_data["gender_Male"] = 1

    if Partner == "Yes":
        input_data["Partner_Yes"] = 1

    if Dependents == "Yes":
        input_data["Dependents_Yes"] = 1

    if PhoneService == "Yes":
        input_data["PhoneService_Yes"] = 1

    # -------- MULTIPLE LINES --------
    if MultipleLines == "Yes":
        input_data["MultipleLines_Yes"] = 1
    elif MultipleLines == "No phone service":
        input_data["MultipleLines_No phone service"] = 1

    # -------- INTERNET --------
    if InternetService == "Fiber optic":
        input_data["InternetService_Fiber optic"] = 1
    elif InternetService == "No":
        input_data["InternetService_No"] = 1

    # -------- ONLINE SECURITY --------
    if OnlineSecurity == "Yes":
        input_data["OnlineSecurity_Yes"] = 1
    elif OnlineSecurity == "No internet service":
        input_data["OnlineSecurity_No internet service"] = 1

    # -------- ONLINE BACKUP --------
    if OnlineBackup == "Yes":
        input_data["OnlineBackup_Yes"] = 1
    elif OnlineBackup == "No internet service":
        input_data["OnlineBackup_No internet service"] = 1

    # -------- DEVICE PROTECTION --------
    if DeviceProtection == "Yes":
        input_data["DeviceProtection_Yes"] = 1
    elif DeviceProtection == "No internet service":
        input_data["DeviceProtection_No internet service"] = 1

    # -------- TECH SUPPORT --------
    if TechSupport == "Yes":
        input_data["TechSupport_Yes"] = 1
    elif TechSupport == "No internet service":
        input_data["TechSupport_No internet service"] = 1

    # -------- STREAMING TV --------
    if StreamingTV == "Yes":
        input_data["StreamingTV_Yes"] = 1
    elif StreamingTV == "No internet service":
        input_data["StreamingTV_No internet service"] = 1

    # -------- STREAMING MOVIES --------
    if StreamingMovies == "Yes":
        input_data["StreamingMovies_Yes"] = 1
    elif StreamingMovies == "No internet service":
        input_data["StreamingMovies_No internet service"] = 1

    # -------- CONTRACT --------
    if Contract == "One year":
        input_data["Contract_One year"] = 1
    elif Contract == "Two year":
        input_data["Contract_Two year"] = 1

    # -------- BILLING --------
    if PaperlessBilling == "Yes":
        input_data["PaperlessBilling_Yes"] = 1

    # -------- PAYMENT --------
    if PaymentMethod == "Credit card":
        input_data["PaymentMethod_Credit card (automatic)"] = 1
    elif PaymentMethod == "Electronic check":
        input_data["PaymentMethod_Electronic check"] = 1
    elif PaymentMethod == "Mailed check":
        input_data["PaymentMethod_Mailed check"] = 1

    # -------- PREDICTION --------
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error("⚠️ Customer is likely to churn")
    else:
        st.success("✅ Customer is likely to stay")

